### ISSUE TITLE
re: Server Not Working Announcment- will it come back or is this project dead?

### ISSUE THREAD

**Issue by xnghu** [staniel359/muffon#47] opened 2022-05-06 03:41 UTC
Just curious if this project will come back? I had just barely begun using it when then it stopped working and I see your announcement on the Read Me- just curious if I should check back, or if this is the end?

**Comment by staniel359** [comment] 2022-05-06 05:59
@xnghu Hello.
Yes, it will come back.
With new features even.

The issue is the main server's hard drive has stopped working.
So right now I'm moving to another server and should setup some infrastructure and test it.
And there's also an issue with hard drive's data.
Right now it's not clear whether it's recoverable or not, so I'm waiting for my fellow technician's response.

So basically the app's next version (beta.2) will be working already.

**Comment by xnghu** [comment] 2022-05-06 14:19
fantastic news, thanks for the answer! looking forward to beta.2 :) 
& I appreciate your work here, muffon is a great project!

**Comment by staniel359** [comment] 2022-05-06 14:41
@xnghu Thank you.
I'm sorry for the technical difficulties.

**Closed as completed by staniel359** 2022-05-06 14:41 UTC
Labels: question
